### ISSUE TITLE
nightly build is failing with `rmw_qos_profile_rosout_default`

### ISSUE THREAD

**Issue by fujitatomoya** [fujitatomoya/rcl_logging_syslog#94]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System:

Ubuntu 24.04

### ROS version or commit hash:

Rolling

### RMW implementation:

Any

### 'ros2 doctor --report' output

```Formatted

```

### Steps to reproduce issue

https://github.com/fujitatomoya/rcl_logging_syslog/actions/runs/13053182661/job/36417820639

```shell
/tmp/colcon_ws/src/rcl/rcl/src/rcl/node_options.c: In function ‘rcl_node_get_default_options’:
/tmp/colcon_ws/src/rcl/rcl/src/rcl/node_options.c:40:19: error: ‘rmw_qos_profile_rosout_default’ undeclared (first use in this function); did you mean ‘rcl_qos_profile_rosout_default’?
   40 |     .rosout_qos = rmw_qos_profile_rosout_default,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   rcl_qos_profile_rosout_default
/tmp/colcon_ws/src/rcl/rcl/src/rcl/node_options.c:40:19: note: each undeclared identifier is reported only once for each function it appears in
gmake[2]: *** [CMakeFiles/rcl.dir/build.make:356: CMakeFiles/rcl.dir/src/rcl/node_options.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:264: CMakeFiles/rcl.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
```

### Expected behavior

Nightly build passes.

### Actual behavior

Nightly build fails.

**Comment by fujitatomoya** [comment]
this build failure is introduced by https://github.com/ros2/rcl/commit/c9b3220759d55f039ef954f5cddadb59c28cc2fa

the mainline is no problem, because all dependent changes are merged all together.
but the problem for this repo is that during nightly build, it just clones latest `rcl` and build with `rcl_logging_syslog`, that is missing `rmw` latest change since it tries to build them on `rolling` container.

a couple of things that we can do here,

- always use latest source build instead of released `rolling` container environment. this can catch up with mainline development source code, but it does not verify the release environment.
- use `rcl` release tag aligns with released `rolling` environment.

**Comment by fujitatomoya** [comment]
> always use latest source build instead of released rolling container environment. this can catch up with mainline development source code, but it does not verify the release environment.

Since this requires to build the `rcl` with it, there could be possibility that this kind of dependency problem happens. that said, i think this is the correct way to proceed to make sure `rcl_logging_syslog` with `rcl` does not get build-breaking problem like this.

- `ros2-builder` to create the ros2 builder docker images for each distribution. all build dependencies are installed in the container, so we can just start the source build with `vcs import & colcon build --pacakges-up-to xxx`. this can be another github project, and periodically run the script to push the images to the dockerhub.
- use those ros2 builder images in this repository github workflow to build the latest source up to this repository. that guarantees that this project is built with the latest mainline source code nightly.
